// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdXXWndcVa43SV7eXFxAF8evftutFFycU',
    appId: '1:359770526845:web:a3f82b55ded7add3c68d14',
    messagingSenderId: '359770526845',
    projectId: 'sem5finalproject-30816',
    authDomain: 'sem5finalproject-30816.firebaseapp.com',
    storageBucket: 'sem5finalproject-30816.appspot.com',
    measurementId: 'G-WLZXPQV4ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM3l940DkXDLNwmWjhhelDDzNh0_vF85E',
    appId: '1:359770526845:android:f8ff701b3c3f4757c68d14',
    messagingSenderId: '359770526845',
    projectId: 'sem5finalproject-30816',
    storageBucket: 'sem5finalproject-30816.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc9MHmoxnVHF4w_VibobE7tAcJZm5InYA',
    appId: '1:359770526845:ios:1791a2c1cadd50a0c68d14',
    messagingSenderId: '359770526845',
    projectId: 'sem5finalproject-30816',
    storageBucket: 'sem5finalproject-30816.appspot.com',
    iosClientId: '359770526845-s96auhcftb6e0jrhlag3aol2b41eec17.apps.googleusercontent.com',
    iosBundleId: 'com.example.sem5finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc9MHmoxnVHF4w_VibobE7tAcJZm5InYA',
    appId: '1:359770526845:ios:46567368b08a7b93c68d14',
    messagingSenderId: '359770526845',
    projectId: 'sem5finalproject-30816',
    storageBucket: 'sem5finalproject-30816.appspot.com',
    iosClientId: '359770526845-lv2qbvo6mjffh8bkkh2lgj7t2a1n2eli.apps.googleusercontent.com',
    iosBundleId: 'com.example.sem5finalproject.RunnerTests',
  );
}
